name: Main

on:
  push:
    branches: [ "webvision-cpp" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "webvision-cpp" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    container:
      image: debian:buster
    env:
      BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v3

    - name: Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get update
        apt-get install -y --no-install-recommends ca-certificates curl gpg make gcc g++ git-core
        curl https://deepviewml.com/apt/key.pub | gpg --dearmor -o /usr/share/keyrings/deepviewml.gpg
        echo 'deb [signed-by=/usr/share/keyrings/deepviewml.gpg] https://deepviewml.com/apt stable main' > /etc/apt/sources.list.d/deepviewml.list
        apt-get update
        apt-get install -y --no-install-recommends libvideostream-dev libvaal-dev libdeepview-rt-dev libzmq3-dev libturbojpeg0-dev

    - name: Dependencies (aarch64)
      if: matrix.arch == 'aarch64'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        dpkg --add-architecture arm64
        apt-get update
        apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libvideostream:arm64 libvaal:arm64 libdeepview-rt:arm64 libzmq3-dev:arm64 libturbojpeg0-dev:arm64

    - name: Build
      run: make CXX=${{ matrix.arch }}-linux-gnu-g++ APP=webvision-linux-${{ matrix.arch }}

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: webvision-linux-${{ matrix.arch }}
